replicaCount: 2

image:
  repository: 218804696766.dkr.ecr.us-east-1.amazonaws.com/orders
  tag: ""          # defaults to .Chart.AppVersion; set by pipeline
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests: { cpu: 50m, memory: 64Mi }
  limits:   { cpu: 200m, memory: 128Mi }

ingress:
  enabled: false
