kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 15d
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
  grafana:
    enabled: false
