## Deployed to namespace: cert-manager
cert-manager:
  enabled: true
  crds:
    enabled: true
  replicaCount: 2
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

ingress-nginx:    { enabled: false }
metrics-server:   { enabled: false }
prometheus:       { enabled: false }
loki:             { enabled: false }
grafana:          { enabled: false }
promtail:         { enabled: false }
external-dns:     { enabled: false }
