## Deployed to namespace: ingress-nginx
ingress-nginx:
  enabled: true
  controller:
    replicaCount: 2
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

# All other components disabled
cert-manager:     { enabled: false }
metrics-server:   { enabled: false }
prometheus:       { enabled: false }
loki:             { enabled: false }
grafana:          { enabled: false }
promtail:         { enabled: false }
external-dns:     { enabled: false }
