## Deployed to namespace: kube-system
metrics-server:
  enabled: true
  args:
    - --kubelet-preferred-address-types=InternalIP
    - --kubelet-insecure-tls
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

ingress-nginx:    { enabled: false }
cert-manager:     { enabled: false }
prometheus:       { enabled: false }
loki:             { enabled: false }
grafana:          { enabled: false }
promtail:         { enabled: false }
external-dns:     { enabled: false }
