## Deployed to namespace: logging
promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  serviceMonitor:
    enabled: true

ingress-nginx:    { enabled: false }
cert-manager:     { enabled: false }
metrics-server:   { enabled: false }
prometheus:       { enabled: false }
loki:             { enabled: false }
grafana:          { enabled: false }
external-dns:     { enabled: false }
