## Deployed to namespace: monitoring
prometheus:
  enabled: true
  grafana:
    enabled: false    # standalone grafana used instead
  prometheus:
    prometheusSpec:
      retention: 15d
      retentionSize: "40GB"
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
      serviceMonitorSelectorNilUsesHelmValues: false
  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

ingress-nginx:    { enabled: false }
cert-manager:     { enabled: false }
metrics-server:   { enabled: false }
loki:             { enabled: false }
grafana:          { enabled: false }
promtail:         { enabled: false }
external-dns:     { enabled: false }
