apiVersion: v2
name: loki
description: Loki log aggregation system (single-binary, filesystem storage)
type: application
version: 0.1.0
dependencies:
  - name: loki
    version: "5.47.2"
    repository: https://grafana.github.io/helm-charts
