---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helmfile-cmp-cm
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helmfile
    spec:
      allowConcurrency: true
      discover:
        find:
          command: [sh, -c, "find . -maxdepth 1 -name 'helmfile.yaml' | head -1"]
      generate:
        command:
          - sh
          - -c
          - |
            helmfile repos 2>/dev/null || true
            helmfile deps 2>/dev/null || true
            helmfile template --quiet --include-crds 2>/dev/null
      lockRepo: false
