spec:
  template:
    spec:
      volumes:
        - name: helmfile-cmp-cm
          configMap:
            name: helmfile-cmp-cm
        - name: custom-tools
          emptyDir: {}
      initContainers:
        - name: copy-helmfile
          image: ghcr.io/helmfile/helmfile:v0.167.1
          command:
            - sh
            - -c
            - cp $(which helmfile) /custom-tools/helmfile && chmod +x /custom-tools/helmfile
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
      containers:
        - name: helmfile-plugin
          image: quay.io/argoproj/argocd:v2.10.7
          command: [/var/run/argocd/argocd-cmp-server]
          env:
            - name: HELM_CACHE_HOME
              value: /helm-working-dir
            - name: HELM_CONFIG_HOME
              value: /helm-working-dir
            - name: HELM_DATA_HOME
              value: /helm-working-dir
            - name: PATH
              value: /custom-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
            - name: var-files
              mountPath: /var/run/argocd
            - name: plugins
              mountPath: /home/argocd/cmp-server/plugins
            - name: tmp
              mountPath: /tmp
            - name: helm-working-dir
              mountPath: /helm-working-dir
            - name: helmfile-cmp-cm
              mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
