apiVersion: v2
name: grafana
description: Grafana dashboards with Prometheus and Loki datasources
type: application
version: 0.1.0
dependencies:
  - name: grafana
    version: "7.3.11"
    repository: https://grafana.github.io/helm-charts
