apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: paas-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Platform infrastructure — all 8 components"

  sourceRepos:
    - "*"

  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paas-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: paas-infra
  source:
    repoURL: https://github.com/vishalliverpool/Umbrella-arogocd-deployment.git
    targetRevision: HEAD
    path: paas-umbrella
    helm:
      releaseName: platform
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - Validate=false
