apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sinec-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vishalliverpool/Umbrella-arogocd-deployment.git
    targetRevision: main
    path: sinec-app
    helm:
      releaseName: sinec-app
  destination:
    server: https://kubernetes.default.svc
    namespace: sinec-app           # all 3 microservices land here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
